version: '3.9'

services:
  front:
    container_name: Frontend-js
    build: ./Front
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./Front/src:/usr/share/nginx/html
    networks:
      alta_disponibilidad:

  cliente:
    container_name: cliente-flask
    build: ./Backend/Cliente
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./Backend/Cliente:/cliente
    depends_on:
      - server
    networks:
      alta_disponibilidad:
    
  server:
    container_name: server
    build: ./Backend/Server
    restart: always
    ports:
      - 50051:50051
    volumes:
      - ./Backend/Server:/server
    depends_on:
      - db
    networks:
      alta_disponibilidad:
        ipv4_address: 172.23.0.5

  db:
    image: mongo:6.0.3
    container_name: db-mongo
    restart: always
    ports:
      - 27018:27017
    env_file:
      - common.env
    volumes:
      - ./db/datadir:/data/db
    networks:
      alta_disponibilidad:

  selenium:
    container_name: scrapper
    build:
      context: ./Webscrapping
      dockerfile: Dockerfile
    command: tail -f /dev/null
    volumes:
      - ./Webscrapping/app:/app
    networks:
      alta_disponibilidad:
    
networks:
  alta_disponibilidad:
    name: malba_sempai
    driver: bridge
    ipam:
      config:
        - subnet: "172.23.0.0/16"
          gateway: "172.23.0.1"