version: '3.9'

services:
  front:
    container_name: Frontend-js
    build: ./Front
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./Front/src:/usr/share/nginx/html

  backend:
    container_name: Backend-flask
    build: ./Backend
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./Backend:/app
      - ./protos:/app/protos
    depends_on:
      - db

  db:
    image: mongo:6.0.3
    container_name: db-mongo
    restart: always
    ports:
      - 8081:8081
    env_file:
      - common.env
    volumes:
      - ./db/datadir:/data/db
    