version: '3.9'

services:
  front:
    container_name: Frontend-js
    build: ./Front
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./Front/src:/usr/share/nginx/html

  cliente:
    container_name: cliente-flask
    build: ./Backend/Cliente
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./Backend/Cliente:/cliente
    depends_on:
      - server
    
  server:
    container_name: server
    build: ./Backend/Server
    restart: always
    ports:
      - 50051:50051
    volumes:
      - ./Backend/Server:/server
    depends_on:
      - db

  db:
    image: mongo:6.0.3
    container_name: db-mongo
    restart: always
    ports:
      - 8081:8081
    env_file:
      - common.env
    volumes:
      - ./db/datadir:/data/db
    