kind: Service
apiVersion: v1
metadata:
  name: front
  namespace: andrunose
spec:
  ports:
    - name: cce-service-0
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: front
    version: v1
  type: LoadBalancer
  sessionAffinity: None
  loadBalancerIP: 182.160.26.111
  externalTrafficPolicy: Cluster
status:
  loadBalancer: {}
