kind: Service
apiVersion: v1
metadata:
  name: front
  namespace: andrunose
  uid: d4ee01de-6a23-4a66-a6a1-b491a17af28d
  resourceVersion: '26752'
  creationTimestamp: '2022-12-21T06:40:44Z'
  labels:
    app: front
    name: front
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.health-check-flag: 'on'
    kubernetes.io/elb.health-check-option: '{"protocol":"TCP","delay":"5","timeout":"10","max_retries":"3"}'
    kubernetes.io/elb.id: 3b43ad22-5948-4712-ab25-7c30042f109d
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  managedFields:
    - manager: Go-http-client
      operation: Update
      apiVersion: v1
      time: '2022-12-21T06:40:44Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubernetes.io/elb.class': {}
            'f:kubernetes.io/elb.health-check-flag': {}
            'f:kubernetes.io/elb.health-check-option': {}
            'f:kubernetes.io/elb.id': {}
            'f:kubernetes.io/elb.lb-algorithm': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:name': {}
        'f:spec':
          'f:externalTrafficPolicy': {}
          'f:loadBalancerIP': {}
          'f:ports':
            .: {}
            'k:{"port":8080,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector':
            .: {}
            'f:app': {}
            'f:version': {}
          'f:sessionAffinity': {}
          'f:type': {}
    - manager: huawei-cloud-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-12-21T06:40:44Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:finalizers':
            .: {}
            'v:"service.kubernetes.io/load-balancer-cleanup"': {}
spec:
  ports:
    - name: cce-service-0
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30617
  selector:
    app: front
    version: v1
  clusterIP: 10.247.159.36
  clusterIPs:
    - 10.247.159.36
  type: LoadBalancer
  sessionAffinity: None
  loadBalancerIP: 182.160.26.111
  externalTrafficPolicy: Cluster
status:
  loadBalancer: {}
