kind: Service
apiVersion: v1
metadata:
  name: cliente
  namespace: andrunose
  uid: d30584a3-7ad6-4681-9684-3c758f939f9a
  resourceVersion: '24879'
  creationTimestamp: '2022-12-21T06:32:52Z'
  labels:
    app: cliente
    name: cliente
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.health-check-flag: 'on'
    kubernetes.io/elb.health-check-option: '{"protocol":"TCP","delay":"5","timeout":"10","max_retries":"3"}'
    kubernetes.io/elb.id: 3b43ad22-5948-4712-ab25-7c30042f109d
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  managedFields:
    - manager: huawei-cloud-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-12-21T06:32:57Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:finalizers':
            .: {}
            'v:"service.kubernetes.io/load-balancer-cleanup"': {}
        'f:status':
          'f:loadBalancer':
            'f:ingress': {}
    - manager: Go-http-client
      operation: Update
      apiVersion: v1
      time: '2022-12-21T06:34:28Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubernetes.io/elb.class': {}
            'f:kubernetes.io/elb.health-check-flag': {}
            'f:kubernetes.io/elb.health-check-option': {}
            'f:kubernetes.io/elb.id': {}
            'f:kubernetes.io/elb.lb-algorithm': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:name': {}
        'f:spec':
          'f:externalTrafficPolicy': {}
          'f:loadBalancerIP': {}
          'f:ports':
            .: {}
            'k:{"port":5000,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:nodePort': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector':
            .: {}
            'f:app': {}
            'f:version': {}
          'f:sessionAffinity': {}
          'f:type': {}
spec:
  ports:
    - name: cce-service-0
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32094
  selector:
    app: cliente
    version: v1
  clusterIP: 10.247.174.212
  clusterIPs:
    - 10.247.174.212
  type: LoadBalancer
  sessionAffinity: None
  loadBalancerIP: 182.160.26.111
  externalTrafficPolicy: Cluster
status:
  loadBalancer:
    ingress:
      - ip: 182.160.26.111
      - ip: 192.168.0.23