kind: Service
apiVersion: v1
metadata:
  name: cliente
spec:
  ports:
    - name: cce-service-0
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: cliente
    version: v1
  type: LoadBalancer
  sessionAffinity: None
  loadBalancerIP: 182.160.26.111
  externalTrafficPolicy: Cluster
status:
  loadBalancer:
    ingress:
      - ip: 182.160.26.111
      - ip: 192.168.0.23