kind: Service
apiVersion: v1
metadata:
  name: service-mongo
  namespace: andrunose
  resourceVersion: v1
spec:
  ports:
    - name: cce-service-0
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongo
    version: v1
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}