kind: Service
apiVersion: v1
metadata:
  name: service-servidor
  namespace: andrunose
  resourceVersion: '156187'
spec:
  ports:
    - name: cce-service-0
      protocol: TCP
      port: 50051
      targetPort: 50051
  selector:
    app: servidor
    version: v1
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}