# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import myproto_pb2 as myproto__pb2


class MyServiceStub(object):
    """Servicio que retorna la temperatura actual en grados centígrados, el valor de la UF en pesos chilenos, el valor del dólar en pesos chilenos y un enlace a un crucigrama online
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetData = channel.unary_unary(
                '/mypackage.MyService/GetData',
                request_serializer=myproto__pb2.Empty.SerializeToString,
                response_deserializer=myproto__pb2.Data.FromString,
                )


class MyServiceServicer(object):
    """Servicio que retorna la temperatura actual en grados centígrados, el valor de la UF en pesos chilenos, el valor del dólar en pesos chilenos y un enlace a un crucigrama online
    """

    def GetData(self, request, context):
        """Retorna la temperatura actual en grados centígrados, el valor de la UF en pesos chilenos, el valor del dólar en pesos chilenos y un enlace a un crucigrama online
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetData,
                    request_deserializer=myproto__pb2.Empty.FromString,
                    response_serializer=myproto__pb2.Data.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mypackage.MyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MyService(object):
    """Servicio que retorna la temperatura actual en grados centígrados, el valor de la UF en pesos chilenos, el valor del dólar en pesos chilenos y un enlace a un crucigrama online
    """

    @staticmethod
    def GetData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mypackage.MyService/GetData',
            myproto__pb2.Empty.SerializeToString,
            myproto__pb2.Data.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
