# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: myproto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmyproto.proto\x12\tmypackage\"[\n\x04\x44\x61ta\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08uf_value\x18\x02 \x01(\x02\x12\x14\n\x0c\x64ollar_value\x18\x03 \x01(\x02\x12\x16\n\x0e\x63rossword_link\x18\x04 \x01(\t\"\x07\n\x05\x45mpty29\n\tMyService\x12,\n\x07GetData\x12\x10.mypackage.Empty\x1a\x0f.mypackage.Datab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myproto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATA._serialized_start=28
  _DATA._serialized_end=119
  _EMPTY._serialized_start=121
  _EMPTY._serialized_end=128
  _MYSERVICE._serialized_start=130
  _MYSERVICE._serialized_end=187
# @@protoc_insertion_point(module_scope)
